// Code generated by protoc-gen-gogo. DO NOT EDIT.
// deprecated/deprecated.proto is a deprecated file.

// package deprecated contains only deprecated messages and services.

package deprecated

import (
	context "context"
	fmt "fmt"
	proto "github.com/cockroachdb/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DeprecatedEnum contains deprecated values.
type DeprecatedEnum int32 // Deprecated: Do not use.
const (
	// DEPRECATED is the iota value of this enum.
	DeprecatedEnum_DEPRECATED DeprecatedEnum = 0 // Deprecated: Do not use.
)

var DeprecatedEnum_name = map[int32]string{
	0: "DEPRECATED",
}

var DeprecatedEnum_value = map[string]int32{
	"DEPRECATED": 0,
}

func (x DeprecatedEnum) String() string {
	return proto.EnumName(DeprecatedEnum_name, int32(x))
}

func (DeprecatedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f64ba265cd7eae3f, []int{0}
}

// DeprecatedRequest is a request to DeprecatedCall.
//
// Deprecated: Do not use.
type DeprecatedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeprecatedRequest) Reset()         { *m = DeprecatedRequest{} }
func (m *DeprecatedRequest) String() string { return proto.CompactTextString(m) }
func (*DeprecatedRequest) ProtoMessage()    {}
func (*DeprecatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64ba265cd7eae3f, []int{0}
}
func (m *DeprecatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprecatedRequest.Unmarshal(m, b)
}
func (m *DeprecatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprecatedRequest.Marshal(b, m, deterministic)
}
func (m *DeprecatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprecatedRequest.Merge(m, src)
}
func (m *DeprecatedRequest) XXX_Size() int {
	return xxx_messageInfo_DeprecatedRequest.Size(m)
}
func (m *DeprecatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprecatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeprecatedRequest proto.InternalMessageInfo

// Deprecated: Do not use.
type DeprecatedResponse struct {
	// DeprecatedField contains a DeprecatedEnum.
	DeprecatedField DeprecatedEnum `protobuf:"varint,1,opt,name=deprecated_field,json=deprecatedField,proto3,enum=deprecated.DeprecatedEnum" json:"deprecated_field,omitempty"` // Deprecated: Do not use.
	// DeprecatedOneof contains a deprecated field.
	//
	// Types that are valid to be assigned to DeprecatedOneof:
	//
	//	*DeprecatedResponse_DeprecatedOneofField
	DeprecatedOneof      isDeprecatedResponse_DeprecatedOneof `protobuf_oneof:"deprecated_oneof"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *DeprecatedResponse) Reset()         { *m = DeprecatedResponse{} }
func (m *DeprecatedResponse) String() string { return proto.CompactTextString(m) }
func (*DeprecatedResponse) ProtoMessage()    {}
func (*DeprecatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64ba265cd7eae3f, []int{1}
}
func (m *DeprecatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprecatedResponse.Unmarshal(m, b)
}
func (m *DeprecatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprecatedResponse.Marshal(b, m, deterministic)
}
func (m *DeprecatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprecatedResponse.Merge(m, src)
}
func (m *DeprecatedResponse) XXX_Size() int {
	return xxx_messageInfo_DeprecatedResponse.Size(m)
}
func (m *DeprecatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprecatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeprecatedResponse proto.InternalMessageInfo

type isDeprecatedResponse_DeprecatedOneof interface {
	isDeprecatedResponse_DeprecatedOneof()
}

type DeprecatedResponse_DeprecatedOneofField struct {
	DeprecatedOneofField string `protobuf:"bytes,2,opt,name=deprecated_oneof_field,json=deprecatedOneofField,proto3,oneof" json:"deprecated_oneof_field,omitempty"`
}

func (*DeprecatedResponse_DeprecatedOneofField) isDeprecatedResponse_DeprecatedOneof() {}

func (m *DeprecatedResponse) GetDeprecatedOneof() isDeprecatedResponse_DeprecatedOneof {
	if m != nil {
		return m.DeprecatedOneof
	}
	return nil
}

// Deprecated: Do not use.
func (m *DeprecatedResponse) GetDeprecatedField() DeprecatedEnum {
	if m != nil {
		return m.DeprecatedField
	}
	return DeprecatedEnum_DEPRECATED
}

// Deprecated: Do not use.
func (m *DeprecatedResponse) GetDeprecatedOneofField() string {
	if x, ok := m.GetDeprecatedOneof().(*DeprecatedResponse_DeprecatedOneofField); ok {
		return x.DeprecatedOneofField
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeprecatedResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeprecatedResponse_DeprecatedOneofField)(nil),
	}
}

func init() {
	proto.RegisterEnum("deprecated.DeprecatedEnum", DeprecatedEnum_name, DeprecatedEnum_value)
	proto.RegisterType((*DeprecatedRequest)(nil), "deprecated.DeprecatedRequest")
	proto.RegisterType((*DeprecatedResponse)(nil), "deprecated.DeprecatedResponse")
}

func init() { proto.RegisterFile("deprecated/deprecated.proto", fileDescriptor_f64ba265cd7eae3f) }

var fileDescriptor_f64ba265cd7eae3f = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x3b, 0x2b, 0x88, 0xee, 0xa1, 0xd6, 0x45, 0x34, 0x44, 0x94, 0x92, 0x53, 0x10, 0x9a,
	0x40, 0xbd, 0xf5, 0x66, 0x9a, 0x88, 0x3d, 0x29, 0xb1, 0x27, 0x2f, 0x92, 0x6c, 0xa6, 0x69, 0x30,
	0xcd, 0xc6, 0x64, 0xe3, 0x33, 0xf8, 0x3e, 0x5e, 0x7c, 0x3c, 0xd9, 0x58, 0xdc, 0x2d, 0xd8, 0xcb,
	0xb0, 0x3b, 0xf3, 0xff, 0xcd, 0x27, 0xbd, 0xcc, 0xb0, 0x6e, 0x90, 0x27, 0x12, 0x33, 0x5f, 0x3f,
	0xbd, 0xba, 0x11, 0x52, 0x30, 0xaa, 0x3d, 0xce, 0x05, 0x3d, 0x0d, 0xff, 0x7e, 0x31, 0xbe, 0x77,
	0xd8, 0xca, 0x19, 0xb1, 0xc0, 0xf9, 0x02, 0xca, 0xcc, 0x48, 0x5b, 0x8b, 0xaa, 0x45, 0xb6, 0xa0,
	0x23, 0x4d, 0xbf, 0xae, 0x0a, 0x2c, 0x33, 0x0b, 0xc6, 0xe0, 0x0e, 0xa7, 0xb6, 0x67, 0x14, 0xd2,
	0x64, 0x54, 0x75, 0x9b, 0x80, 0x58, 0x10, 0x9f, 0xe8, 0xf0, 0xbd, 0xc2, 0xd8, 0x8c, 0x9e, 0x1b,
	0xa9, 0x44, 0x85, 0x62, 0xb5, 0x4d, 0x48, 0xc6, 0xe0, 0x1e, 0x2b, 0xe8, 0x61, 0x10, 0x9f, 0x69,
	0xcd, 0xa3, 0x92, 0xf4, 0xac, 0xea, 0x30, 0x60, 0x3b, 0xad, 0xf4, 0xfc, 0x8d, 0x4b, 0x87, 0xbb,
	0xa5, 0x19, 0xa3, 0x34, 0x8c, 0x9e, 0xe2, 0x68, 0x7e, 0xb7, 0x8c, 0xc2, 0xd1, 0xc0, 0x26, 0x47,
	0x60, 0x13, 0x0b, 0xa6, 0x95, 0x39, 0xf8, 0x33, 0x36, 0x1f, 0x05, 0x47, 0xb6, 0x34, 0xf1, 0x79,
	0x52, 0x96, 0xec, 0xea, 0xff, 0xa9, 0xb6, 0x9b, 0xb2, 0xaf, 0xf7, 0x85, 0x7f, 0xd7, 0xe5, 0x1c,
	0x7c, 0x12, 0xb0, 0x95, 0x09, 0x16, 0x2f, 0x61, 0x5e, 0xc8, 0x75, 0x97, 0x7a, 0x5c, 0x6c, 0x7c,
	0x2e, 0xf8, 0x5b, 0x23, 0x12, 0xbe, 0xce, 0x52, 0x3f, 0x17, 0xb9, 0xe8, 0x0f, 0xe3, 0xf7, 0x96,
	0x4f, 0x72, 0xac, 0x26, 0xca, 0xe9, 0x4b, 0x6c, 0x65, 0x96, 0xc8, 0xc4, 0x38, 0xe1, 0x37, 0x40,
	0x7a, 0xd8, 0xeb, 0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x05, 0x72, 0x71, 0xe5, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeprecatedServiceClient is the client API for DeprecatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
//
// Deprecated: Do not use.
type DeprecatedServiceClient interface {
	// DeprecatedCall takes a DeprecatedRequest and returns a DeprecatedResponse.
	DeprecatedCall(ctx context.Context, in *DeprecatedRequest, opts ...grpc.CallOption) (*DeprecatedResponse, error)
}

type deprecatedServiceClient struct {
	cc *grpc.ClientConn
}

// Deprecated: Do not use.
func NewDeprecatedServiceClient(cc *grpc.ClientConn) DeprecatedServiceClient {
	return &deprecatedServiceClient{cc}
}

// Deprecated: Do not use.
func (c *deprecatedServiceClient) DeprecatedCall(ctx context.Context, in *DeprecatedRequest, opts ...grpc.CallOption) (*DeprecatedResponse, error) {
	out := new(DeprecatedResponse)
	err := c.cc.Invoke(ctx, "/deprecated.DeprecatedService/DeprecatedCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeprecatedServiceServer is the server API for DeprecatedService service.
//
// Deprecated: Do not use.
type DeprecatedServiceServer interface {
	// DeprecatedCall takes a DeprecatedRequest and returns a DeprecatedResponse.
	DeprecatedCall(context.Context, *DeprecatedRequest) (*DeprecatedResponse, error)
}

// Deprecated: Do not use.
// UnimplementedDeprecatedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeprecatedServiceServer struct {
}

func (*UnimplementedDeprecatedServiceServer) DeprecatedCall(ctx context.Context, req *DeprecatedRequest) (*DeprecatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeprecatedCall not implemented")
}

// Deprecated: Do not use.
func RegisterDeprecatedServiceServer(s *grpc.Server, srv DeprecatedServiceServer) {
	s.RegisterService(&_DeprecatedService_serviceDesc, srv)
}

func _DeprecatedService_DeprecatedCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeprecatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeprecatedServiceServer).DeprecatedCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deprecated.DeprecatedService/DeprecatedCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeprecatedServiceServer).DeprecatedCall(ctx, req.(*DeprecatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeprecatedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deprecated.DeprecatedService",
	HandlerType: (*DeprecatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeprecatedCall",
			Handler:    _DeprecatedService_DeprecatedCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deprecated/deprecated.proto",
}
